language: node_js
node_js:
  - 4.2
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - node_modules
notifications:
  email:
    - torstenlink@gmx.de
    - markus.felten@gmx.de
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
  - chmod 777 ./test/travis/setup_arangodb.sh
  - ./test/travis/setup_arangodb.sh
script:
  - npm run-script cover
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success:
  - npm run semantic-release
